// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// e_step_nvnorm_em
arma::mat e_step_nvnorm_em(const arma::mat& data, const arma::vec& mu, const arma::mat& Sigma);
RcppExport SEXP _DATA501Package_e_step_nvnorm_em(SEXP dataSEXP, SEXP muSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(e_step_nvnorm_em(data, mu, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// e_step_nvnorm_mcem
Rcpp::List e_step_nvnorm_mcem(const arma::mat& data, const arma::vec& mu, const arma::mat& Sigma, const int m, const int burn, const int thin, const double tau);
RcppExport SEXP _DATA501Package_e_step_nvnorm_mcem(SEXP dataSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP mSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(e_step_nvnorm_mcem(data, mu, Sigma, m, burn, thin, tau));
    return rcpp_result_gen;
END_RCPP
}
// e_step_poisson_em
arma::mat e_step_poisson_em(const arma::mat& data, const arma::vec& lambda);
RcppExport SEXP _DATA501Package_e_step_poisson_em(SEXP dataSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(e_step_poisson_em(data, lambda));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_nvnorm
double log_likelihood_nvnorm(const arma::mat& data, const arma::vec& mu, const arma::mat& Sigma);
RcppExport SEXP _DATA501Package_log_likelihood_nvnorm(SEXP dataSEXP, SEXP muSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_nvnorm(data, mu, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_poisson
double log_likelihood_poisson(const arma::mat& data, const arma::vec& lambda);
RcppExport SEXP _DATA501Package_log_likelihood_poisson(SEXP dataSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_poisson(data, lambda));
    return rcpp_result_gen;
END_RCPP
}
// m_step_nvnorm
Rcpp::List m_step_nvnorm(const arma::mat& imputed_data);
RcppExport SEXP _DATA501Package_m_step_nvnorm(SEXP imputed_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type imputed_data(imputed_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(m_step_nvnorm(imputed_data));
    return rcpp_result_gen;
END_RCPP
}
// m_step_poisson
Rcpp::List m_step_poisson(const arma::mat& imputed_data);
RcppExport SEXP _DATA501Package_m_step_poisson(SEXP imputed_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type imputed_data(imputed_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(m_step_poisson(imputed_data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DATA501Package_e_step_nvnorm_em", (DL_FUNC) &_DATA501Package_e_step_nvnorm_em, 3},
    {"_DATA501Package_e_step_nvnorm_mcem", (DL_FUNC) &_DATA501Package_e_step_nvnorm_mcem, 7},
    {"_DATA501Package_e_step_poisson_em", (DL_FUNC) &_DATA501Package_e_step_poisson_em, 2},
    {"_DATA501Package_log_likelihood_nvnorm", (DL_FUNC) &_DATA501Package_log_likelihood_nvnorm, 3},
    {"_DATA501Package_log_likelihood_poisson", (DL_FUNC) &_DATA501Package_log_likelihood_poisson, 2},
    {"_DATA501Package_m_step_nvnorm", (DL_FUNC) &_DATA501Package_m_step_nvnorm, 1},
    {"_DATA501Package_m_step_poisson", (DL_FUNC) &_DATA501Package_m_step_poisson, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_DATA501Package(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
