# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

e_step_nvnorm_em <- function(data, mu, Sigma) {
    .Call(`_DATA501Package_e_step_nvnorm_em`, data, mu, Sigma)
}

e_step_nvnorm_mcem <- function(data, mu, Sigma, m, burn, thin, tau) {
    .Call(`_DATA501Package_e_step_nvnorm_mcem`, data, mu, Sigma, m, burn, thin, tau)
}

e_step_poisson_em <- function(data, lambda) {
    .Call(`_DATA501Package_e_step_poisson_em`, data, lambda)
}

log_likelihood_nvnorm <- function(data, mu, Sigma) {
    .Call(`_DATA501Package_log_likelihood_nvnorm`, data, mu, Sigma)
}

log_likelihood_poisson <- function(data, lambda) {
    .Call(`_DATA501Package_log_likelihood_poisson`, data, lambda)
}

m_step_nvnorm <- function(imputed_data) {
    .Call(`_DATA501Package_m_step_nvnorm`, imputed_data)
}

m_step_poisson <- function(imputed_data) {
    .Call(`_DATA501Package_m_step_poisson`, imputed_data)
}

