# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

e_step_nvnorm <- function(data, mu, Sigma) {
    .Call(`_DATA501Package_e_step_nvnorm`, data, mu, Sigma)
}

log_likelihood_nvnorm <- function(data, mu, Sigma) {
    .Call(`_DATA501Package_log_likelihood_nvnorm`, data, mu, Sigma)
}

m_step_nvnorm <- function(imputed_data) {
    .Call(`_DATA501Package_m_step_nvnorm`, imputed_data)
}

